### ISSUE TITLE
Das erste Wort

### ISSUE THREAD

**Issue by phter** [phter/gravity#10]
Wer das liest und mutig ist, schreibt eine Antwort :)

**Comment by jank99** [comment]
Hallo :). Können wir dir auch Code schicken, der (noch) nicht funktioniert?

**Comment by phter** [comment]
na sicher!
am anfang funktioniert sowie niemals nix, das ist ganz normal

**Comment by jank99** [comment]
Ich habe jetzt ein bisschen Code hochgeladen (siehe dazu die anderen Issues).

**Comment by phter** [comment]
@jank99 hier kannst du nichts hochladen, das kann nur ich :)
du musst rechts oben bei meinem repository auf "fork" klicken, dann erzeugst du eine kopie von meinem repository, wo du dann sachen hochladen kannst.
und dann am besten kurze nachricht an mich, dann kann ichs mir von deinem repository holen.

**Comment by jank99** [comment]
Danke, ich glaube, jetzt hat es funktioniert.
LG Jan

Am 12.06.2019 23:34 schrieb "philipp weinfurter" <notifications@github.com>:
