### ISSUE TITLE
Langsamer Spielstart

### ISSUE THREAD

**Issue by phter** [phter/gravity#12]
Man kann sich jetzt die Gravitation als Heatmap und als Vektorplot ansehen.
Finde, das sieht recht geil aus.
ABER, die Berechnung der Vektoransicht dauert sehr lange - nicht mein Fehler, die benutzte Bibliothek (matplotlib) braucht einfach lange dafuer. Da kann ich nichts machen.
Was tun? Diese Ansicht wieder rausschmeissen?
Oder ein Popup mit 'Please wait...'?
Vorschlaege?

**Comment by jank99** [comment]
Wollte es mir gerade ansehen, aber bei der neuesten Version werden bei mir leider keine Planeten angezeigt. Bei dir funktioniert es, oder?

**Comment by jank99** [comment]
Also ich kann sogar die Rakete starten (in den Labels werden der verbrauchte Treibstoff und der Start angezeigt), aber ich sehe nur den blauen Hintergrund im Mainframe.

**Comment by phter** [comment]
Sehr seltsam... hast du die pakete matplotlib und PIL installiert?

**Comment by phter** [comment]
bzw. siehst du in der Konsole eine Fehlermeldung?

**Comment by jank99** [comment]
Die Pakete sind installiert. Wenn ich auf "New Game" klicke, werden die Planeten erzeugt, aber später kommt folgende Fehlermeldung:
AttributeError: module 'matplotlib' has no attribute 'figure'

**Comment by phter** [comment]
sch.....ade. ok, schau ich mir heut am abend an, danke!

**Comment by jank99** [comment]
@phter auf den Uni-PCs gibt es genau dasselbe Problem wie auf meinem Laptop

Am 17.06.2019 13:42 schrieb "philipp weinfurter" <notifications@github.com>:

> sch.....ade. ok, schau ich mir heut am abend an, danke!
>

**Comment by phter** [comment]
Neue Version ist hochgeladen. Sollte jetzt funktionieren, bitte testen!

**Comment by jank99** [comment]
Jawohl, es funktioniert :)

**Comment by phter** [comment]
Fixed
