### ISSUE TITLE
Weitere Anzeigen

### ISSUE THREAD

**Issue by phter** [phter/gravity#5]
- Anzahl bisheriger Starts
- Zurueckgelegter Weg
- Verbrauchter Treibstoff

**Comment by jank99** [comment]
Ich habe auf zwei verschiedene Arten versucht, die Labels zu erstellen, nämlich beim ersten Mal jede Anzeige in einem einzelnen Label und beim zweiten Mal alle Anzeigen in einem Label. Allerdings habe ich es (noch) nicht geschafft, dass die Labels upgedatet werden. Ich habe versucht, sie gemeinsam mit der Uhr upzudaten, was aber nicht funktioniert hat.

**Comment by jank99** [comment]
Hab das Updaten der Labels jetzt hinbekommen :). Ich arbeite noch ein bisschen dran und lade morgen dann den Code hoch

**Comment by jank99** [comment]
bzw. heute

**Comment by phter** [comment]
OK! Ich hab inzwischen eine neue Version hochgeladen.
Lass dich davon nicht irritieren, ich kann deinen Code trotzdem
uebernehmen, wenn's soweit ist.
lg

**Comment by jank99** [comment]
Ich habe 2 Labels hinzugefügt, nämlich die Anzahl der Starts und die Anzahl der Flüge aus unserem Universum hinaus. Die anderen beiden Labels, die du vorgeschlagen hast, wären komplizierter gewesen, soweit ich das sehen konnte: Der Treibstoffverbrauch bleibt nämlich noch konstant bei 0, hängt also noch nicht vom Flug der Rakete ab. Ich denke, dass vor allem das Label mit der Anzahl der Starts wichtig ist, weil man sonst bei hoher Animationsgeschwindigkeit manchmal nicht unterscheiden kann, ob die Rakete losgeflogen und am selben Planeten wieder gelandet ist oder ob sie gar nicht erst losgeflogen ist.

**Comment by phter** [comment]
Hab einige Aenderungen gemacht, weil mittlerweise die GUI anders ausschaut, sollte aber passen.
