### ISSUE TITLE
Spielstand laden / speichern

### ISSUE THREAD

**Issue by phter** [phter/gravity#6]
In den Projektanforderungen steht, dass Dateihandling dabei sein soll....
Also muessen irgendwas laden / speichern.

**Comment by phter** [comment]
Einfachere Variante: die Einstellungen laden / speichern. Es gibt eine Menge Regler, mit denen man spielen kann. Diese Werte koennte man speichern und beim naechsten Mal wieder laden.

**Comment by jank99** [comment]
Ich habe zwei Funktionen dafür erstellt. Hoffe, die funktionieren :)

**Comment by jank99** [comment]
Ich habe das Laden und Speichern des Spielstandes hinbekommen. Wenn man das Spiel mit "Quit" beendet, werden in der Datei "settings.txt" die Einstellungen der ersten acht Slider gespeichert und beim nächsten Öffnen des Spiels wieder eingelesen. Der Code dazu ist zwar nicht sonderlich elegant, aber immerhin funktioniert er :).

**Comment by phter** [comment]
@jank99 Super! Hab nur einen kurzen Blick drauf geworfen. Bei ein paar Sachen muss man noch etwas rumfeilen. Wird sich vielleicht bis zur Praesentation nicht ausgehen, ist aber egal, es gibt genug herzuzeigen. 
Die zusaetzlichen Anzeigen hab ich uebernommen und etwas umgeschrieben, weil sich der Code seither etwas geaendert hat.

**Comment by jank99** [comment]
@phter Ich hab nochmal am Speichern der Werte der Schieberegler gearbeitet. Am Ende des Spiels werden die Werte jetzt in einem Dictionary gespeichert. Am Beginn des nächsten Spiels kann der String dann einfach wieder in ein Dictionary umgewandelt werden. Allerdings habe ich mit einer älteren Version gearbeitet, also weiß ich nicht, ob du das noch verwenden kannst.

**Comment by phter** [comment]
done
